name: Build and push container image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: public.ecr.aws
  NAMESPACE: nasa-veda
  IMAGE_NAME: ssim-ghg-workshop-2024-r-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    
    - uses: int128/create-ecr-repository-action@v1
      with:
        repository: ${{ env.IMAGE_NAME}}
        public: true

    - name: Set outputs
      id: sha_short
      run: echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-12)" >> $GITHUB_OUTPUT

    - name: Build container image
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
        REPO_DIR: /srv/repo
        NO_PUSH: "true"

    - name: Push to Amazon ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.sha_short.outputs.sha_short }}
